version: "3.9"
    
services:

  zenoh-bridge:
    image: eclipse/zenoh-bridge-ros2dds:nightly
    container_name: zenoh-bridge
    environment:
      - ROS_DISTRO=humble
      - ROS_DOMAIN_ID=1
      - ROS_LOCALHOST_ONLY=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host
    # networks:
    #   - turtlebot_net
    # ports:
    #   - 7449:7447
    #   - 8002:8002
    command: -e tcp/192.168.199.112:7447 -i turtlebot3 # --rest-http-port 8000

  turtlebot3-gui:
    build:
      context: ./turtlebot3_gui
      dockerfile: Dockerfile
    container_name: turtlebot3-gui
    network_mode: host
    depends_on:
      - turtlebot3-server
    # networks:
    #   - turtlebot_net
    # ports:
    #   - 8765:8765

  turtlebot3-server:
    build:
      context: ./turtlebot3_server
      dockerfile: Dockerfile
    container_name: turtlebot3-server
    environment:
      - ROS_DOMAIN_ID=1
      - ROS_LOCALHOST_ONLY=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host
    # networks:
    #   - turtlebot_net
    # ports:
    #   - 8765:8765
    # command: flask --app server run
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml


  foxglove-studio:
    image: ghcr.io/foxglove/studio:latest
    container_name: foxglove-studio
    network_mode: host
    depends_on:
      - turtlebot3-server
    # networks:
    #   - turtlebot_net
    # ports:
    #   - 8080:8080
    volumes:
      - ./foxglove/foxglove-layout.json:/foxglove/default-layout.json