version: "3.9"

# networks:
#   turtlebot_net:
#     name: turtlebot_net
    
services:

  zenoh-bridge:
    image: eclipse/zenoh-bridge-ros2dds:nightly
    container_name: zenoh-bridge
    environment:
      - ROS_DISTRO=humble
      - ROS_DOMAIN_ID=1
      - ROS_LOCALHOST_ONLY=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host
    # networks:
    #   - turtlebot_net
    # ports:
    #   - 7449:7447
    #   - 8002:8002
    # command: -e tcp/192.168.175.45:7447 -i 0A0B23 --rest-http-port 8002

  foxglove-bridge:
    build:
      context: ./foxglove
      dockerfile: Dockerfile
    container_name: foxglove-bridge
    environment:
      - ROS_DOMAIN_ID=1
      - ROS_LOCALHOST_ONLY=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host
    # networks:
    #   - turtlebot_net
    # ports:
    #   - 8765:8765
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8765

  foxglove-studio:
    image: ghcr.io/foxglove/studio:latest
    container_name: foxglove-studio
    network_mode: host
    depends_on:
      - foxglove-bridge
    # networks:
    #   - turtlebot_net
    # ports:
    #   - 8080:8080
    volumes:
      - ./foxglove/foxglove-layout.json:/foxglove/default-layout.json