version: "3.9"

networks:
  turtlebot_net:
    name: turtlebot_net

services:

  turtlebot3:
    build:
      context: ./src/turtlebot3
      dockerfile: Dockerfile
    container_name: turtlebot3
    environment:
      - QT_X11_NO_MITSHM=1
      - DISPLAY=$DISPLAY
      - ROS_DOMAIN_ID=112
      # - ROS_LOCALHOST_ONLY=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - TURTLEBOT3_MODEL=burger
    networks:
      - turtlebot_net
    command: ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py

  zenoh_bridge:
    image: eclipse/zenoh-bridge-ros2dds:nightly
    environment:
      - ROS_DISTRO=humble
      - ROS_DOMAIN_ID=112
      # - ROS_LOCALHOST_ONLY=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    networks:
      - turtlebot_net
    ports:
      - 8000:8000
    command: -l tcp/0.0.0.0:7447 --rest-http-port 8000 -i 0A0B23